### ISSUE TITLE
The thumbnail used is still jpg.

### ISSUE THREAD

**Issue by guugg** [adamsilverstein/modern-images-wp#11]
The thumbnail used is still jpg.
How to show webp in the media?
Or let the thumbnail support automatic webp?

**Comment by adamsilverstein** [comment]
@guugg - can you check tools -> site health to make sure your server supports webp? Are you using WordPress 5.8?

**Comment by adamsilverstein** [comment]
Closing as inactive, feel free to re-open @guugg if this is still an issue.
