### ISSUE TITLE
Fatal Error with plugin -

### ISSUE THREAD

**Issue by AcmeLDN** [adamsilverstein/modern-images-wp#16]
Hi!

Would love for this too work, please see below.

can't select an option in the dropdown either see image

WordPress version 5.8
Current plugin: Modern Images WP (version 1.0.1)
PHP version 7.4.21

![Screen Shot 2021-07-28 at 17 53 20](https://user-images.githubusercontent.com/88138401/127468333-3865fa8c-425e-4f45-9dc5-d05eb80a177a.png)

Error

`An error of type E_ERROR was caused in line 195 of the file /var/www/vhosts/web.co.uk/web.co.uk/wp-content/plugins/modern-images-wp-main/src/Setting.php. Error message: Uncaught Error: Call to undefined function Modern_Images_WP\str_to_upper() in /var/www/vhosts/web.co.uk/web.co.uk/wp-content/plugins/modern-images-wp-main/src/Setting.php:195
Stack trace:
#0 /var/www/vhosts/web.co.uk/web.co.uk/wp-content/plugins/modern-images-wp-main/src/Setting.php(117): Modern_Images_WP\Setting->isImageFormatSupported()
#1 /var/www/vhosts/web.co.uk/web.co.uk/wp-admin/includes/template.php(1743): Modern_Images_WP\Setting->Modern_Images_WP\{closure}()
#2 /var/www/vhosts/web.co.uk/web.co.uk/wp-admin/includes/template.php(1701): do_settings_fields()
#3 /var/www/vhosts/web.co.uk/web.co.uk/wp-admin/options-media.php(156): do_settings_sections()
#4 {main}
 thrown`

**Comment by adamsilverstein** [comment]
Thanks for reporting @AcmeLDN - Fixed in #17
